# Generated by Django 6.0.4 on 2026-04-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_ai_summary_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
